<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<script>
    Promise.resolve('1')
        .finally(() => {
            console.log('finally1')
            throw new Error('我是finally中抛出的异常')
        })
        .then(res => {
            console.log('finally后面的then函数', res)
        })
        .catch(err => {
            console.log('捕获错误', err)
        })

    // finally1 捕获错误：我是finally中抛出的异常
</script>
</html>